### ISSUE TITLE
Binary asset management

### ISSUE THREAD

**Issue by n7st** [snoonetIRC/static-web#1]
In 1a3729c8599e5d5af23cbc8709120c202eb5571f, binary assets (PNG, SVG files) were added to the repository. Ideally these wouldn't be kept in git, and should be hosted elsewhere. Any ideas / preferences?

**Comment by linuxdaemon** [comment]
Hm, I would prefer to avoid keeping binary assets in VCS but it seems the easiest way to allow everyone access to them. It also seems other projects do something similar, https://github.com/xsf/xmpp.org/tree/d7ae72979d2cb1340b5f0fcd4091641244057c2a/content/images for instance

**Comment by A-UNDERSCORE-D** [comment]
so long as they're not overly large and added/removed a bunch it should be fine. The size increase on the repo should be marginal

**Comment by n7st** [comment]
Agreed, let's keep things in here for now.
