### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by n7st** [snoonetIRC/static-web#27]
There are two separate license files: one in the top level directory, one in the theme. These both need setting to the _actual_ license (when we decide what it is).

**Comment by n7st** [comment]
I think we're safe to go with the MIT license. Existing content was written for Snoonet, and the layout was designed for it by staff who are still on (I believe diss and Paradox?).

Input welcome, of course.

**Comment by flotwig** [comment]
IANAL, but I think that sounds fine.
