### ISSUE TITLE
Mobile styles are busted

### ISSUE THREAD

**Issue by flotwig** [snoonetIRC/static-web#33]
![image](https://user-images.githubusercontent.com/1151760/51430718-0107d380-1bed-11e9-9ed8-8ec89748decc.png)

**Comment by flotwig** [comment]
This is from the web inspector `iPhone 5/SE` setting, but it's also broken on others.

**Comment by n7st** [comment]
Yep, broken from my M8. I'll look at fixing things on Thursday unless anyone can get there ahead of me.

For the time being, let's aim to have it "working" with the existing screen CSS, and then maybe have a project to have a full mobile version later.
