### ISSUE TITLE
Change title to Snoonet IRC network

### ISSUE THREAD

**Issue by flotwig** [snoonetIRC/static-web#34]
<A_Dragon> can we change that title to "Snoonet IRC network"?

**Comment by n7st** [comment]
The global site title? We could maybe set a subtitle param up, "IRC network", and have that display in the top {{ .Title }}. Reason being, "Snoonet IRC network - Page title" in the tab would be quite wordy.

**Comment by flotwig** [comment]
"Snoonet IRC Network" for /, and then just "$pageTitle - Snoonet IRC" for all other pages would be cool. Is that possible?

**Comment by n7st** [comment]
Something like:

```
Snoonet
{{ if eq .Url "/" }}
    IRC Network
{{ else }}
    &middot; {{ .Title }}
{{ end }}
```

**Comment by n7st** [comment]
Or set `Title` in the front matter of the site's index page (`content/posts/_index.md`, I think?)
