### ISSUE TITLE
Content organisation and permalink changes

### ISSUE THREAD

**Issue by n7st** [snoonetIRC/static-web#6]
**Proposal**: Organise content into subdirectories for tidiness and sanity preservation.

On our existing site, there isn't any URL namespacing as such, meaning things like staff pages (`/mike`) and community pages (`/asianbeauty`) are at the top level.

With Hugo (and the other static site generators I've tried), URL paths relate to the way content is organised. This means that (in the top level "content" directory) an item in `community/channelname.md` will have a URL of `/community/channelname`.

In order to have dynamic index pages (i.e. for staff and community sections), the namespaces will be different than the existing live site. I can't see any issue for staff (mine will be `/staff/mike`), but it might be worth checking channel topics and possibly subreddits for links to community pages.

In the existing site there are also "rules" pages which might be better organised into `/community/communityname/rules`, and again will probably need checking against channel topics.

Are there any other concerns?

## Required redirections

Please let me know if you change any content which will require a redirection.

(old, new)

* All community pages (`/communityname`, `/community/name`)
* `/streetfighterrules`, `/community/streetfighter/rules`
* `/r4rrules`, `/community/r4r/rules`
* `/aspergersrules`, `/community/aspergers/rules`
* `/troll_nsfw`, `/community/troll_nsfw/rules`
* `/troll_politics`, `/community/troll_politics/rules`
* `/depressionalt`, `/community/depression-alt/rules`
* `/ccrules`, `/community/casualconversation/rules`
* `/neopetsrules`, `/community/neopets/rules`
* `/anxietymods`, `/community/anxiety/mods`
* `/partymansion`, `/community/partymansion/rules`
* `/connect-auth`, `/help/#Authing%20on%20connect`
* `/support`, `https://support.snoonet.org`
* `/status`, `https://status.snoonet.org`

**Comment by linuxdaemon** [comment]
The namespacing makes sense to me, to handle the migration we could do temporary `location` blocks in nginx to permanent redirect to the new location for existing pages and just have new pages always use the new links, at least for community pages and stuff

**Comment by n7st** [comment]
Another potential solution are URL aliases, [documented here](https://gohugo.io/content-management/urls/).

**Comment by n7st** [comment]
# Out of date content

There's quite a lot of old and long out-of-date content on the website, such as posts about new servers which no longer exist. We could drop these from our current content by setting their `draft` values to `true`.

"Historically significant" content such as staff changeovers should probably be left alone.

Proposed content to prune:

* https://github.com/snoonetIRC/static-web/blob/master/content/posts/2016/09/23/new-servers.md
* https://github.com/snoonetIRC/static-web/blob/master/content/posts/2016/12/11/channel-operator-tools.md
* https://github.com/snoonetIRC/static-web/blob/master/content/posts/2016/12/15/update.md

Please feel free to discuss.

**Comment by flotwig** [comment]
You can also just set the `url` in the front-matter, if I'm reading this correctly. It'll override any other path-related options you set and just plop it where you tell it to.

https://gohugo.io/content-management/urls/#override-urls-with-front-matter

**Comment by n7st** [comment]
Ideally, we'd be moving towards namespacing the content a little better (to avoid collisions), which was why I was leaning towards aliases, which can also be set in page front matter:

```
---
aliases:
- "/posts/my-original-url/",
- "/2010/01/01/even-earlier-url.html"
[...]
---
```

**Comment by flotwig** [comment]
Yeah, I was thinking more from a "don't break existing links" perspective. But we can just set up a ton of `rewrite permanent`'s if we want to do it the right way moving forward.

If the same content is available at multiple URLs, that is worse for SEO. Is that what aliases are? If so it might be best just to do the rewrites on the nginx side.

**Comment by n7st** [comment]
Yes - that would work. I think the aliases could be used to the same effect
(they'd just duplicate the pages in the generated site rather than being at
the web server level).

**Comment by n7st** [comment]
It's a question of how is best to manage them - @linuxdaemon would you
prefer them in the nginx Puppet configs or in the site's content? I think I
agree with @flotwig that the permanent rewrites are the best solution
because it keeps the site content focused rather than polluting it with
additional config.
